# This file was generated by GoReleaser. DO NOT EDIT.
cask "tf-import-gen" do
  version "0.19.3"

  on_macos do
    on_arm do
      sha256 "65064753fb6f50e8b6046a2b64a8ce5c7b05f01528d1539c983a31fe3b243d10"
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v#{version}/tf-import-gen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8cc0cffa557feaedeb61e329eaa0a091b80b3cf7fee8af7ac51f28dad44133c"
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v#{version}/tf-import-gen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f539197f693a804983337d2e9b0c173eb6a1be44109e4a1a004739645e935e0f"
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v#{version}/tf-import-gen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d39fb76a268766559005cd231cf14efed0657a2e4e4e82d4ad32758c761b4ec0"
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v#{version}/tf-import-gen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tf-import-gen"
  desc "Tool to generate terraform import statements to simplify state migrations from one terraform code base to another"
  homepage "https://github.com/kishaningithub/tf-import-gen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tf-import-gen"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tf-import-gen"]
    end
  end

  # No zap stanza required
end
