# This file was generated by GoReleaser. DO NOT EDIT.
cask "tf-import-gen" do
  version "0.19.2"

  on_macos do
    on_arm do
      sha256 "07c33db4dcaf849212477e1db800cb08ff0ed1cced618a43196a1d434ca163b9"
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v#{version}/tf-import-gen_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "58ec35369e7ec71da04cc72336a7f4e2cb5a066cfce96e43d3df3a8cf51a4988"
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v#{version}/tf-import-gen_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8ae39898ba836f390ee128a74047e312ef56fd129875e8259976e411f26219e0"
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v#{version}/tf-import-gen_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "55e17173e225e9a83610444532fad6bd84f1f2c56cd1448fdc56fa4a37932072"
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v#{version}/tf-import-gen_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tf-import-gen"
  desc "Tool to generate terraform import statements to simplify state migrations from one terraform code base to another"
  homepage "https://github.com/kishaningithub/tf-import-gen"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tf-import-gen"

  # No zap stanza required
end
