# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dynadump < Formula
  desc "Export your dynamoDB data as JSON"
  homepage "https://github.com/kishaningithub/dynadump"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/dynadump/releases/download/v0.1.0/dynadump_0.1.0_darwin_amd64.tar.gz"
      sha256 "5c273dcfbfd6de90af92a997f75ea23cd59fe21a594e7c46aa06a129f83bd5bb"

      def install
        bin.install "dynadump"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/dynadump/releases/download/v0.1.0/dynadump_0.1.0_darwin_arm64.tar.gz"
      sha256 "4e384ef90a3f122ed0a7e95629a770cdc940254d621a3b1c7d17cdd9af1057c7"

      def install
        bin.install "dynadump"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kishaningithub/dynadump/releases/download/v0.1.0/dynadump_0.1.0_linux_amd64.tar.gz"
        sha256 "52a209813ca17cf576d4370f4f30125f8bb46417f45adc8eaa984465793c3aec"

        def install
          bin.install "dynadump"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kishaningithub/dynadump/releases/download/v0.1.0/dynadump_0.1.0_linux_arm64.tar.gz"
        sha256 "a98103fef69104bb7f1ed1b57b89145dfd6310e742bbb7d7ff62cf8842d884b5"

        def install
          bin.install "dynadump"
        end
      end
    end
  end
end
