# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaConsoleAvroWithoutSchemaRegistry < Formula
  desc "Tail kafka avro topic data without confluent schema registry overhead"
  homepage "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry"
  version "0.2.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry/releases/download/v0.2.2/kafka-console-avro-without-schema-registry_0.2.2_darwin_amd64.tar.gz"
      sha256 "8af61b8b01febadddacafa8115ee8730976913697efc5ad2b13ae7071ec4151d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry/releases/download/v0.2.2/kafka-console-avro-without-schema-registry_0.2.2_darwin_arm64.tar.gz"
      sha256 "a5c0283c7b12d22429e056733abbd4195c533c52fa6b2a60183a834d87d467b1"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry/releases/download/v0.2.2/kafka-console-avro-without-schema-registry_0.2.2_linux_amd64.tar.gz"
      sha256 "b7385ec8bccecdd30ea5e70f89e0a46617932a992091314dbe2e545702116c81"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry/releases/download/v0.2.2/kafka-console-avro-without-schema-registry_0.2.2_linux_arm64.tar.gz"
      sha256 "36c9afd4803b3f5979d7a62319858ef6d9827d205be4d112f32c6e99a73873a1"
    end
  end

  def install
    bin.install "kafka-console-avro-without-schema-registry"
  end
end
