# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaPerf < Formula
  desc "Tail kafka avro topic data without confluent schema registry overhead"
  homepage "https://github.com/kishaningithub/kafka-perf"
  version "0.0.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.0.2/kafka-perf_0.0.2_darwin_amd64.tar.gz"
      sha256 "00bfa845035ebbbacaa83febdd95d80fca1248b2ced2fdbfcb1ce6ba36e781d8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.0.2/kafka-perf_0.0.2_darwin_arm64.tar.gz"
      sha256 "e2140f8c7f124104554a4614e999d4659dd59a97de351e90b02f2321048f2be6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.0.2/kafka-perf_0.0.2_linux_amd64.tar.gz"
      sha256 "2fda6f8a4898de8be37420240b5b7872ad6b9b5819f58f7fa9f85b6b85580aa6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.0.2/kafka-perf_0.0.2_linux_arm64.tar.gz"
      sha256 "dd20f2fd543f4ea4d985411590908e3850e4d2010ef5cf8ee64e57e0a10e0743"
    end
  end

  def install
    bin.install "kafka-perf"
  end
end
