# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaConsoleAvroWithoutSchemaRegistry < Formula
  desc "Tail kafka avro topic data without confluent schema registry overhead"
  homepage "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry"
  version "0.4.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry/releases/download/v0.4.0/kafka-console-avro-without-schema-registry_0.4.0_darwin_amd64.tar.gz"
      sha256 "8b90db77ecfd02e44ccaf736d87089eb73f802d113c64fca0236b24292bedf9e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry/releases/download/v0.4.0/kafka-console-avro-without-schema-registry_0.4.0_darwin_arm64.tar.gz"
      sha256 "ce02f3f6cce67ef10c71ec727e0e607c431b90065d2f6e1993c7161d79118b6f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry/releases/download/v0.4.0/kafka-console-avro-without-schema-registry_0.4.0_linux_amd64.tar.gz"
      sha256 "c95dc42c9b25d634ad883daeec7a4d06a0f09c1d74da00e21e88c79256fbe3fa"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/kafka-console-avro-without-schema-registry/releases/download/v0.4.0/kafka-console-avro-without-schema-registry_0.4.0_linux_arm64.tar.gz"
      sha256 "a13fde45bf1ea097bcd084df9cdd5dfceb145efb0a6c50a383aafefca678866d"
    end
  end

  def install
    bin.install "kafka-console-avro-without-schema-registry"
  end
end
