# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaPerf < Formula
  desc "Tail kafka avro topic data without confluent schema registry overhead"
  homepage "https://github.com/kishaningithub/kafka-perf"
  version "0.0.7"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.0.7/kafka-perf_0.0.7_darwin_amd64.tar.gz"
      sha256 "01e8970bd9f391abfe9c299911c5a4ba29e466296083650ecb73b82a92855318"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.0.7/kafka-perf_0.0.7_darwin_arm64.tar.gz"
      sha256 "a0cb5201953dbe6dd0110e0acf7586a2224ba6556fc7c6ad3ae0713509cd4c80"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.0.7/kafka-perf_0.0.7_linux_amd64.tar.gz"
      sha256 "ae98ad6bcf7342a6fb809d87ed294678a06a17a93bd9315eef23aef4f01c3894"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.0.7/kafka-perf_0.0.7_linux_arm64.tar.gz"
      sha256 "d9717fdccc4d681ed7b7aaa445881fd05c11e837eb0b4069ec6cd0045cbb43b6"
    end
  end

  def install
    bin.install "kafka-perf"
  end
end
