# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KafkaPerf < Formula
  desc "Tail kafka avro topic data without confluent schema registry overhead"
  homepage "https://github.com/kishaningithub/kafka-perf"
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.2.0/kafka-perf_0.2.0_darwin_amd64.tar.gz"
      sha256 "056324e51c378d10025ef9bbb7903c8f941a9bec687b60df3dfec044b48fc626"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.2.0/kafka-perf_0.2.0_darwin_arm64.tar.gz"
      sha256 "83e866b2c5814b500928a832dc205eefe53efa947fd70a6b5778155c31f469c8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.2.0/kafka-perf_0.2.0_linux_amd64.tar.gz"
      sha256 "25d75d94b14e90861b249d9508739db0787b636fe7ab0eec093d5fab6e29e148"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/kafka-perf/releases/download/v0.2.0/kafka-perf_0.2.0_linux_arm64.tar.gz"
      sha256 "c7ab6b8ed30ef487e9eeb09896d5b96fa97bdba0d1d09fcda549497651161cb9"
    end
  end

  def install
    bin.install "kafka-perf"
  end
end
