# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MemoryEater < Formula
  desc "Eats memory at a specified constant rate"
  homepage "https://github.com/kishaningithub/memory-eater"
  version "0.0.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.4/memory-eater_0.0.4_darwin_amd64.tar.gz"
      sha256 "eb01e688506a3dbc049a83c840db56e661046c4c064e6e743b813d935987354c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.4/memory-eater_0.0.4_darwin_arm64.tar.gz"
      sha256 "3e01c4384c723e75c4b53114a4a0cafb247337f82f9a5e996ac2a67b562e67d6"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.4/memory-eater_0.0.4_linux_amd64.tar.gz"
      sha256 "340f4d12c28f061d16ac9900c458a904f9c328899c5c17a1d505e554ccaa91b5"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.4/memory-eater_0.0.4_linux_arm64.tar.gz"
      sha256 "fc959e068106aa0329932787b0ee915812850af90542109b80f431b72827aad5"
    end
  end

  def install
    bin.install "memory-eater"
  end
end
