# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MemoryEater < Formula
  desc "Eats memory at a specified constant rate"
  homepage "https://github.com/kishaningithub/memory-eater"
  version "0.0.3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.3/memory-eater_0.0.3_darwin_amd64.tar.gz"
      sha256 "5a5a5fee19bca7dc68c59a3f45c996fa3fab090ff8141774f46bf145cdc6fb7f"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.3/memory-eater_0.0.3_darwin_arm64.tar.gz"
      sha256 "c837983c3e051c56a688874f78f4a8517d537e7410a06cd2e35b6c13df1ce70c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.3/memory-eater_0.0.3_linux_amd64.tar.gz"
      sha256 "b483409e3d098fa3bfc414d4810a11b7bb3c14ca88d139ee0f917b0977a1cedf"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.3/memory-eater_0.0.3_linux_arm64.tar.gz"
      sha256 "c38e26185d8d5613455ce05097c42ff408e8bf9e5905991aa1745d2e1c04d181"
    end
  end

  def install
    bin.install "memory-eater"
  end
end
