# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MemoryEater < Formula
  desc "Eats memory at a specified constant rate"
  homepage "https://github.com/kishaningithub/memory-eater"
  version "0.0.7"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.7/memory-eater_0.0.7_darwin_amd64.tar.gz"
      sha256 "ff36abef1ea4998da50509217768b99fa9de97f253350d1ef543b2ac06d0fa80"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.7/memory-eater_0.0.7_darwin_arm64.tar.gz"
      sha256 "57c77c273f50cd669eb909407b39c2279c2ba9478902ef1a4d988c6960d674b9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.7/memory-eater_0.0.7_linux_amd64.tar.gz"
      sha256 "b978c9554583ccdf3df65e047a7ffdbf6787d2cd18563456a0ef8bba69b4225e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/memory-eater/releases/download/v0.0.7/memory-eater_0.0.7_linux_arm64.tar.gz"
      sha256 "7d06fd8e448b900b36caf165fbd538caea4db458c9d8cc682d1165e2510e690c"
    end
  end

  def install
    bin.install "memory-eater"
  end
end
