# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Randomtext < Formula
  desc "Command line random text generator"
  homepage "https://github.com/kishaningithub/randomtext"
  version "1.0.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/randomtext/releases/download/v1.0.2/randomtext_1.0.2_darwin_amd64.tar.gz"
      sha256 "e796d7abf4dee819aac0ceb21170c7994aa12a398ad7b63a0811da19f7ed7c4b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/randomtext/releases/download/v1.0.2/randomtext_1.0.2_darwin_arm64.tar.gz"
      sha256 "a9a84de2405c55864e0f5b3c2bbb19688150ba46b25a5a85d47a48736c747cc9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/randomtext/releases/download/v1.0.2/randomtext_1.0.2_linux_amd64.tar.gz"
      sha256 "7c6057524060e7d852cfe5e6a54d436b99b514d174de26a1d2f58ed18a29467f"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/randomtext/releases/download/v1.0.2/randomtext_1.0.2_linux_arm64.tar.gz"
      sha256 "08483756d36c7bde1c017696f9a590f64d3b0daee4c76d124b411b87f21edf3a"
    end
  end

  def install
    bin.install "randomtext"
  end
end
