# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rdapp < Formula
  desc "rdapp - redshift data api postgres proxy"
  homepage "https://github.com/kishaningithub/rdapp"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/rdapp/releases/download/v0.5.3/rdapp_0.5.3_darwin_arm64.tar.gz"
      sha256 "854f679db31c90e7b65dd3f012cd0da55c4484b10f1430957f76b284cf2ae689"

      def install
        bin.install "rdapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/rdapp/releases/download/v0.5.3/rdapp_0.5.3_darwin_amd64.tar.gz"
      sha256 "9974a6dd0aee1d79bcc4e5879aa0b363d89d8f58fb86d88c05cf2591fe9d9728"

      def install
        bin.install "rdapp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/rdapp/releases/download/v0.5.3/rdapp_0.5.3_linux_arm64.tar.gz"
      sha256 "176b9bdcb40c508c8196a200f029f839bc96bc4233f9e6dd5273e32d00a9d7c1"

      def install
        bin.install "rdapp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/rdapp/releases/download/v0.5.3/rdapp_0.5.3_linux_amd64.tar.gz"
      sha256 "0bfcbefb00291e88014a01791ac5e746117f9719be4e2376cbc9898c91b01ed0"

      def install
        bin.install "rdapp"
      end
    end
  end
end
