# This file was generated by GoReleaser. DO NOT EDIT.
class ShopifyCsvDownload < Formula
  desc "Download a shopify site in a csv format that the shopify importer understands"
  homepage "https://github.com/kishaningithub/shopify-csv-download"
  version "0.11.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/kishaningithub/shopify-csv-download/releases/download/v0.11.1/shopify-csv-download_0.11.1_darwin_amd64.tar.gz"
    sha256 "f77d135ce2e1763aaa5e581d857281705d0da2ed9fdc2dd841de28c3fcf56f99"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/shopify-csv-download/releases/download/v0.11.1/shopify-csv-download_0.11.1_linux_amd64.tar.gz"
      sha256 "168662af465ad3ddeb70be60ed16e6e60fc9c496f41341ecdfd06f763c2cef67"
    end
  end

  def install
    bin.install "shopify-csv-download"
  end
end
