# This file was generated by GoReleaser. DO NOT EDIT.
class ShopifyCsvDownload < Formula
  desc "Download a shopify site in a csv format that the shopify importer understands"
  homepage "https://github.com/kishaningithub/shopify-csv-download"
  url "https://github.com/kishaningithub/shopify-csv-download/releases/download/v0.6.0/shopify-csv-download_0.6.0_darwin_amd64.tar.gz"
  version "0.6.0"
  sha256 "3b448923e49ed3d8b3638db9ce4c737558fec25aa8c163622a4bd92361982150"

  def install
    bin.install "shopify-csv-download"
  end
end
