# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terralens < Formula
  desc "See your Terraform state world with clarity and precision - TerraLens, your visual command center for infrastructure insight!"
  homepage "https://github.com/kishaningithub/terralens"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/terralens/releases/download/v0.1.0/terralens_0.1.0_darwin_arm64.tar.gz"
      sha256 "b5c244a1c40c797d3838f9841760ee4b7ebb1b09609d90512d45d0bd2dbeeaf7"

      def install
        bin.install "terralens"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/terralens/releases/download/v0.1.0/terralens_0.1.0_darwin_amd64.tar.gz"
      sha256 "c7879851a3c70e169d5ddea996c5166506753a067fd09e56cfbd6079634167dd"

      def install
        bin.install "terralens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/terralens/releases/download/v0.1.0/terralens_0.1.0_linux_amd64.tar.gz"
      sha256 "141f80f8aa222def76edc95fd17a541fd1139f24c211115489a5647dbbb70e26"

      def install
        bin.install "terralens"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/terralens/releases/download/v0.1.0/terralens_0.1.0_linux_arm64.tar.gz"
      sha256 "92d375a4b7c4db9ee6a5310ea29172c2b6b69ea8a57a18670f344d73cf0d5a98"

      def install
        bin.install "terralens"
      end
    end
  end
end
