# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terralens < Formula
  desc "See your Terraform state world with clarity and precision - TerraLens, your visual command center for infrastructure insight!"
  homepage "https://github.com/kishaningithub/terralens"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/terralens/releases/download/v0.0.1/terralens_0.0.1_darwin_amd64.tar.gz"
      sha256 "448df9dc623bc61262a2f81574be684d9d1c73ebbb289f0a851d3a369464ba78"

      def install
        bin.install "terralens"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/terralens/releases/download/v0.0.1/terralens_0.0.1_darwin_arm64.tar.gz"
      sha256 "72ea895665d3c743a092e4d66cfbadc40726260c78c0ab8a029bdcc44440a949"

      def install
        bin.install "terralens"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/terralens/releases/download/v0.0.1/terralens_0.0.1_linux_arm64.tar.gz"
      sha256 "d5bec7e1c1707efbcbc82346f298ea5914c35253e3509949f2ed8f0ad3b1e213"

      def install
        bin.install "terralens"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/terralens/releases/download/v0.0.1/terralens_0.0.1_linux_amd64.tar.gz"
      sha256 "f1dd0c365ecf73a06ec49ea7bec59663cc635d7c6549c5e6cfdcf75e570194c4"

      def install
        bin.install "terralens"
      end
    end
  end
end
