# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfImportGen < Formula
  desc "Tool to generate terraform import statements to simplify state migrations from one terraform code base to another"
  homepage "https://github.com/kishaningithub/tf-import-gen"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v0.19.0/tf-import-gen_0.19.0_darwin_amd64.tar.gz"
      sha256 "49b95cd35586372607c88616cb0ab9d0a87ef3452169612046b92e1a8add33f0"

      def install
        bin.install "tf-import-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v0.19.0/tf-import-gen_0.19.0_darwin_arm64.tar.gz"
      sha256 "92166957be27d0ac9e74cf6fc21767632488283b4009cdebc9d9800cc55f02bb"

      def install
        bin.install "tf-import-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v0.19.0/tf-import-gen_0.19.0_linux_amd64.tar.gz"
      sha256 "aedea05a1724e1381a0bf0a95f24ccd94735de1ff045fb8b343481b787fcd515"
      def install
        bin.install "tf-import-gen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kishaningithub/tf-import-gen/releases/download/v0.19.0/tf-import-gen_0.19.0_linux_arm64.tar.gz"
      sha256 "10b50c317816cd9023cec676ba71eba78445ff59f5a72f6769e8e09694018906"
      def install
        bin.install "tf-import-gen"
      end
    end
  end
end
